name: Synchronize images

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'
  workflow_dispatch: {}
  push:
   branches:
    - main

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Install skopeo
        run: sudo apt-get install -y skopeo

      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Install manifest-tools
        run: go install github.com/estesp/manifest-tool/v2/cmd/manifest-tool@latest
      
      # Upstream Go build fails due to a replace entry in gitlab.com/gitlab-org/cli,
      # so we use the officially built release tarball.
      #- name: Install glab
      #  run: go install gitlab.com/gitlab-org/cli/cmd/glab@latest
      - name: Install glab
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends curl apt-transport-https ca-certificates gnupg
          curl -sSf https://packages.gitlab.com/install/repositories/cli/cli/script.deb.sh | sudo bash
          sudo apt-get install -y glab

      - name: Log in to registry
        run: |
          echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          echo "${{ github.token }}" | skopeo login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: sync
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./sync.sh